name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    environment: PRODUCTION
    needs: cancel
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Stage 1: Go to git folder"
            cd Reactive-Resume

            echo "Stage 2: Stop and remove old container"
            docker stop app-resume || true
            docker rm app-resume || true

            echo "Stage 3: Remove old images"
            docker image prune -af

            echo "Stage 4: Pull latest code from GitHub"
            git checkout .
            git pull origin main

            echo "Stage 5: Build app from Dockerfile"
            docker build -t app-resume .

            echo "Stage 6: Run app"
            docker run -d --env-file ./.env -p 3000:3000 --network reactive-resume_default --restart unless-stopped --name app-resume app-resume

            echo "Done!"

            echo "Stage 7: Remove old images"
            docker image prune -af

            echo "Done!"
